Repository NithyaYamsinghe/ML_Assignment2_IT18233704_IT18156652_IT18213072_IT18209280, pull requests merged in 2022-05, with the labels that each got.

#46 [ml-0001] project readme file updated
  README.md
Labels: enhancement

#47 [ml-0001] project readme file updated
  README.md
Labels: enhancement

#48 [ml-0001] project readme file updated
  README.md
Labels: documentation

#49 [ml-0001] project readme file updated
  README.md
Labels: documentation

#50 [ml-0001] project readme file updated
  README.md
Labels: documentation

#51 [ml-0002] linear regression model import libraries implementation
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
Labels: enhancement

#52 [ml-0003] linear regression model load dataset into data frame implementation
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
Labels: enhancement

#53 [ml-0004] linear regression model dataset preprocessing implementation
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
Labels: implementation

#54 [ml-0005] linear regression model view dataset implementation
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
Labels: implementation

#55 [ml-0006] decision tree model import libraries
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#56 [ml-0007] decision tree model load data into a data frame
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#57 [ml-0008] decision tree model data preprocessing
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#58 [ml-0009] decision tree model view data set
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#59 [ml-0010] decision tree model null value testing and data clearance
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#60 [ml-0011] decision tree model analyze data set
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#61 [ml-0012] decision tree model define x and y
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#62 [ml-0013] decision tree model split train data and test data
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#63 [ml-0014] decision tree model dataset traning and model traning
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#64 [ml-0015] decision tree model comparsion of actual values and predict…
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#65 [ml-0016] decision tree model accuracy and loss function values of th…
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
Labels: implementation

#66 [ml-0017] Stock Price Prediction DataSet
  1. dataset/Stock_Price_Prediction_DataSet.csv
Labels: implementation

#67 [ml-0018] linear regression model dataset cleaning and null value clearance implementation
  1. dataset/README.md
  2. notebooks/Decision_Machine_Learning_For_Stock_Price_Predictio.ipynb
  2. notebooks/Figure 1
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
  2. notebooks/decision_tree_regression_for_stock_price_prediction.ipynb
Labels: enhancement, implementation

#68 [ml-0019] linear regression model analyze dataset implementation
  2. notebooks/Figure 1
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
Labels: enhancement, implementation

#69 [ml-0020] linear regression model view dataset implementation
  2. notebooks/Linear_Regression_For_Stock_Price_Prediction.ipynb
  2. notebooks/decision_tree_regression_model_for_stock_price_prediction.ipynb
  2. notebooks/linear_regression_model_for_stock_price_prediction.ipynb
Labels: implementation

#70 [ml-0021] linear regression model define x and y implementation
  2. notebooks/linear_regression_model_for_stock_price_prediction.ipynb
Labels: implementation

#71 [ml-0021] linear regression model split train and test dataset implementation
  2. notebooks/linear_regression_model_for_stock_price_prediction.ipynb
Labels: implementation

#72 [ml-0022] linear regression model training model implementation
  2. notebooks/linear_regression_model_for_stock_price_prediction.ipynb
Labels: implementation

#73 [ml-0023] linear regression model comparison of predicted and expected values implementation
  2. notebooks/linear_regression_model_for_stock_price_prediction.ipynb
Labels: implementation

#74 [ml-0024] linear regression model accuracy and loss function implementation
  2. notebooks/linear_regression_model_for_stock_price_prediction.ipynb
Labels: implementation

#75 [ml-0025] updated read me files
  1. dataset/README.md
  2. notebooks/README.md
  3. stock_price_prediction_application/README.md
  4. report/README.md
  5. slide_deck/README.md
  6. video_demonstration/README.md
Labels: documentation

#77 [ml-0027] upload slide deck
  2. notebooks/bayesian_ridge_regression_model_for_stock_price_prediction.ipynb
  5. slide_deck/ML_Assignment2_IT18233704_IT18156652_IT18213072_IT18209280.pptx
Labels: documentation
